export const ACTIVITIES = [
  { key: "tennis", label: "Tennis" },
  { key: "table-tennis", label: "Table tennis" },
  { key: "badminton", label: "Badminton" },
  { key: "football", label: "Football" },
  { key: "squash", label: "Squash" },
  { key: "running", label: "Running" },
  { key: "basketball", label: "Basketball" },
  { key: "volleyball", label: "Volleyball" },
  { key: "ski", label: "Ski" },
  { key: "snowboard", label: "Snowboard" },
  { key: "ice-skating", label: "Ice skating" },
  { key: "padel", label: "Padel" },
  { key: "wall-climbing", label: "Wall climbing" },
  { key: "darts", label: "Darts" },
  { key: "paintball", label: "Paintball" },
  { key: "snooker", label: "Snooker" },
  { key: "bowling", label: "Bowling" },
  { key: "karting", label: "Karting" },
  { key: "dance", label: "Dance" },
  { key: "pool", label: "Pool" },
  { key: "golf", label: "Golf" },
  { key: "fitness", label: "Fitness" },
  { key: "boxing", label: "Boxing" },
  { key: "pole-dance", label: "Pole Dance" },
  { key: "baseball", label: "Baseball" },
  { key: "fencing", label: "Fencing" },
  { key: "cycling", label: "Cycling" },
  { key: "motorcycling", label: "Motorcycling" },
  { key: "rafting", label: "Rafting" },
  { key: "kayak", label: "Kayak" },
  { key: "curling", label: "Curling" },
  { key: "petanka", label: "Petanka" },
  { key: "swimming", label: "Swimming" },
  { key: "martial-arts", label: "Martial arts" },
  { key: "horse-riding", label: "Horse riding" },
  { key: "hockey", label: "Hockey" },
  { key: "roller-skating", label: "Roller skating" },
  { key: "yoga", label: "Yoga" },
  { key: "trampolines", label: "Trampolines" },
  { key: "archery", label: "Archery" },
] as const;

export type ActivityKey = (typeof ACTIVITIES)[number]["key"];

export const ACTIVITY_KEYS = ACTIVITIES.map((a) => a.key) as [ActivityKey, ...ActivityKey[]];
